name: final challenge

on:
  push:
    branches: [main]
  pull_request:

env:
  PROJECT_NAME: "ZeroOps"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
            python-version: '3.11'
      - run: echo "$PROJECT_NAME"
      - run: pip install pytest
      - run: python -m pytest
      - run: echo "pipeline successed"
      