name: job-dependencies

on:
  push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Backend tests passing"
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - needs: backend
      - run: echo "Building frontend after backend success"